### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by lukedeo** [lukedeo/adversarial-jets#1]
* [x] We need to not train on the [whole 2M](https://github.com/lukedeo/adversarial-jets/blob/master/models/acgan_jets.py#L147) sample (too long to experiment). Note that these samples are unshuffled and we **need** to shuffle them as there is a big block of signal and a big block of bkg.
* [x] We should convert all [instances](https://github.com/lukedeo/adversarial-jets/blob/master/models/acgan_jets.py#L165) of `U[-1, 1]` noise to `N(0, 1)` noise
* [x] We should make some plotting code to evaluate after training. Maybe start with trying to make some plots for the average jets that look like the ones in the [paper](https://arxiv.org/pdf/1511.05190v2.pdf). There is some code for plotting average / individual jets [here](https://github.com/ml-slac/jet-simulations/blob/master/jettools/jettools.py#L65-L81).
